calibration:
  generated_by: core.mcap_calibration_wizard
  updated_at: '2026-05-03T16:57:43+08:00'
  gripper:
    left:
      calibrated: true
      method: live_gopro_aruco
      image_topic: /gopro_left/image_raw
      output_topic: /gopro_left/gripper_width
      aruco_dict: DICT_4X4_1000
      marker_ids:
      - 0
      - 1
      marker_min: 33.25
      marker_max: 144.522
      closed_detection_rate: 1.0
      open_detection_rate: 1.0
      closed_std_px: 0.0
      open_std_px: 0.0
      closed_frames: 49
      open_frames: 47
      updated_at: '2026-05-03T16:56:16+08:00'
    right:
      calibrated: true
      method: live_gopro_aruco
      image_topic: /gopro_right/image_raw
      output_topic: /gopro_right/gripper_width
      aruco_dict: DICT_4X4_50
      marker_ids:
      - 1
      - 0
      marker_min: 69.029
      marker_max: 233.65
      closed_detection_rate: 1.0
      open_detection_rate: 1.0
      closed_std_px: 0.134
      open_std_px: 0.005
      closed_frames: 35
      open_frames: 34
      updated_at: '2026-05-03T16:57:43+08:00'
  common_frame:
    left:
      calibrated: false
    right:
      calibrated: false
  calibrated: false
  complete: false
batch:
  input_dir: /home/hit/ROS/mcap
  output_dir: /home/hit/ROS/mcap_cleaned
  file_glob: '*.mcap'
  workers: 1
  overwrite: true
  fail_fast: true
transform:
  start_from_common:
    translation:
      x: 0.0
      y: 0.0
      z: 0.0
    rotation_xyzw:
      qx: 0.0
      qy: 0.0
      qz: 0.0
      qw: 1.0
pose_streams:
- input_topic: /baton_mini_left/fast_odom
  msg_type: nav_msgs/msg/Odometry
  output_topic: /baton_mini_left/camera_common_pose
  transform_file: /home/hit/ROS/config/data_clean_left_transform.yaml
- input_topic: /baton_mini_right/fast_odom
  msg_type: nav_msgs/msg/Odometry
  output_topic: /baton_mini_right/camera_common_pose
  transform_file: /home/hit/ROS/config/data_clean_right_transform.yaml
gripper_streams:
- image_topic: /gopro_left/image_raw
  image_msg_type: sensor_msgs/msg/Image
  output_topic: /gopro_left/gripper_width
  output_msg_type: std_msgs/msg/Float32
  aruco_dict: DICT_4X4_1000
  marker_id_0: 0
  marker_id_1: 1
  marker_min: 33.25
  marker_max: 144.522
  gripper_max: 100.0
- image_topic: /gopro_right/image_raw
  image_msg_type: sensor_msgs/msg/Image
  output_topic: /gopro_right/gripper_width
  output_msg_type: std_msgs/msg/Float32
  aruco_dict: DICT_4X4_50
  marker_id_0: 1
  marker_id_1: 0
  marker_min: 69.029
  marker_max: 233.65
  gripper_max: 100.0
